apiVersion: apps/v1
kind: Deployment
metadata:
  name: rz-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rz-dashboard
  template:
    metadata:
      labels:
        app: rz-dashboard
    spec:
      containers:
        - name: rz-dashboard
          image: dhito/rz-dashboard:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rz-dashboard-service
spec:
  selector:
    app: rz-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
