apiVersion: v1
kind: Service
metadata:
  name: rz-dashboard-service
spec:
  selector:
    app: rz-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
